apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: "{{ app_name }}"
    app.kubernetes.io/component: httpd
    app.kubernetes.io/instance: httpd
  name: httpd
  namespace: "{{ ocp_namespace }}"
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 8443-tcp
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    deployment: "{{ app_name }}"
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
